engines:
  eslint:
    enabled: true
  stylelint:
    enabled: true
    channel: "beta"
ratings:
   paths:
   - "src/**/*"
   - "**.js"
exclude_paths:
- "node_modules/"
- "public/"
- "grunt/"
- "tests/"
- "dist/"
